apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8-replica-manager.fullname" . }}
  labels:
    {{- include "k8-replica-manager.labels" . | nindent 4 }}
data:
  LISTEN_ADDR: ":{{ .Values.service.apiPort }}"
  PROBE_LISTEN_ADDR: ":{{ .Values.service.probePort }}"
  TLS_ENABLED: {{ ternary "true" "false" .Values.tls.enabled | quote }}