{{- if and .Values.tls.enabled .Values.tls.createSecret (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "k8-replica-manager.tlsSecretName" . }}
  labels:
    {{- include "k8-replica-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.tls.serverCrtKey }}: {{ .Values.tls.serverCrt | b64enc | quote }}
  {{ .Values.tls.serverKeyKey }}: {{ .Values.tls.serverKey | b64enc | quote }}
  {{ .Values.tls.clientCAKey }}: {{ .Values.tls.clientCA | b64enc | quote }}
{{- end }}
