apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8-replica-manager.serviceAccountName" . }}
  labels:
    {{- include "k8-replica-manager.labels" . | nindent 4 }}
automountServiceAccountToken: true
