apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8-replica-manager.fullname" . }}
  labels:
    {{- include "k8-replica-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "k8-replica-manager.selectorLabels" . | nindent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.apiPort }}
      targetPort: api
